# Use slim python
FROM python:3.11-slim

WORKDIR /app

# install dependencies
COPY app/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# copy app
COPY app /app

EXPOSE 8000

# Use non-root user
RUN useradd -m appuser
USER appuser

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
